BUFFER_SIZE = 2048
HEADER_SIZE = 414
DATA_SIZE = BUFFER_SIZE - HEADER_SIZE

TIMEOUT = 5

LOCAL_HOST = "127.0.0.1"
LOCAL_PORT = 8080

STOP_AND_WAIT = "sw"
SELECTIVE_REPEAT = "sr"

FIRST_SQN = 0

WRITE_MODE = "wb"
READ_MODE = "rb"

DEFAULT_FOLDER = 'saved-files'